micro:
  port:
    dev: "/dev/ttyUSB0"
    socket: "moat.test"
  link:
    guarded: false
    lossy: false
  apps:
    f: moat.micro.app.fs.FsCmd
#   wdt: app.wdt.WDTCmd
# wdt:
#   t: 2000
#   ext: True
