[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools", "wheel",]

[project]
classifiers = [
	"Intended Audience :: Developers",
	"Programming Language :: Python :: 3",
	"Framework :: AsyncIO",
	"Framework :: Trio",
	"Framework :: AnyIO",
	"Development Status :: 4 - Beta",
	]
dependencies = [
	"anyio ~= 4.0",
	"asyncscope",
	"moat-util ~= 0.61.1",
	"moat-db ~= 0.2.5",
	"moat-ems-inv ~= 0.2.12",
	"moat-lib-rpc ~= 0.4.11",
	"moat-lib-codec ~= 0.4.9",
	"moat-lib-config ~= 0.1.0",
	"moat-lib-diffiehellman ~= 0.13.5",
	"moat-lib-gpio ~= 0.9.2",
	"moat-lib-micro ~= 0.1.0",
	"moat-lib-pid ~= 0.6.6",
	"moat-lib-priomap ~= 0.2.2",
	"moat-lib-proxy ~= 0.1.0",
	"moat-lib-ring ~= 0.2.1",
	"moat-lib-run ~= 0.1.0",
	"moat-link ~= 0.2.44",
	"moat-link-server ~= 0.3.24",
	"moat-micro ~= 0.17.10",
	]
version = "0.11.8"
keywords = [ "MoaT",]
requires-python = ">=3.12"
name = "moat"
description = "The command line for MoaT"
#readme = "README.md"

[[project.authors]]
email = "matthias@urlichs.de"
name = "Matthias Urlichs"

[project.scripts]
moat = "moat.main:cmd"

[project.urls]
homepage = "https://m-o-a-t.org"
repository = "https://github.com/M-o-a-T/moat"

[tool.setuptools]
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.yaml"]
